houdini:
  # DSN for backend (uses environment variable by default)
  dsn: '%env(HOUDINI_DSN)%'
  
  # Project ID for telemetry identification (uses environment variable by default)
  project_id: '%env(HOUDINI_PROJECT_ID)%'
  
  # API key for backend authentication (uses environment variable by default)
  api_key: '%env(HOUDINI_API_KEY)%'
  
  # Enable/disable telemetry collection
  enabled: true
  
  # Service identification
  service_name: '%env(HOUDINI_SERVICE_NAME)%'
  service_version: '%env(HOUDINI_SERVICE_VERSION)%'
  
  # Traces configuration
  traces:
    enabled: true
    sample_rate: 1.0  # 0.0 to 1.0
  
  # Metrics configuration
  metrics:
    enabled: true
    export_interval: 60  # seconds
  
  # Logs configuration
  logs:
    enabled: true
    levels: ['error', 'warning', 'info']
  
  # HTTP client configuration
  http_client:
    timeout: 30
